version: '3.7'
services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=kolyan_db
  web:
    build: ./kolyan_project
    command: python kolyan_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/kolyan_project/
    ports:
      - 8000:8000
    depends_on:
      - db
    
volumes:
  postgres_data: