# Generated by Django 4.0.4 on 2022-05-09 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarriageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carriage_category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrainNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=255)),
                ('time_start', models.TimeField(null=True)),
                ('time_stop', models.TimeField(null=True)),
                ('is_end_station', models.BooleanField()),
                ('train_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.traincategory')),
                ('train_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trainnumber')),
            ],
        ),
        migrations.CreateModel(
            name='TrainComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cariage_number', models.IntegerField(null=True)),
                ('cariage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carriagetype')),
                ('train_number_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trainnumber')),
            ],
        ),
    ]
