# Generated by Django 4.0.4 on 2022-05-09 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traincomposition',
            old_name='cariage_id',
            new_name='cariage',
        ),
        migrations.RenameField(
            model_name='traincomposition',
            old_name='train_number_id',
            new_name='train_number',
        ),
    ]
